name: 'CI/CD'
on:
  push:
    branches:
    - master
    paths:
    - '_build_flag'
jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: .
      CG_TOKEN: ${{ secrets.CG_TOKEN }}
      AWS_REGION: us-east-1
      S3BUCKET: ${{ secrets.S3BUCKET }}
      TASK_PASSWORD: ${{ secrets.TASK_PASSWORD }}
      EMAIL: ${{ secrets.EMAIL }}
    
    steps:
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout Code
      uses: actions/checkout@v1 
         
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Download Dependencies
      run: |
          npm install -g https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
    - name: Run Cloudguard Proact
      run: |
          
          cloudguard proact -C ./template.cft -t $CG_TOKEN    
          
    - name: Run Cloudguard FSP
      run: |
          cloudguard fsp add -C ./template.cft --region ${AWS_REGION} -t $CG_TOKEN
            
    - name: Upload Protected CFT
      uses: actions/upload-artifact@v2
      with:
       name: template.protected.cft
       path: ./template.protected.cft
   
    - name: Deploy to AWS
      run: |
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip awscliv2.zip
           sudo ./aws/install 
           aws cloudformation deploy --template-file ./template.protected.cft --stack-name CPTask --parameter-overrides Bucket=$S3BUCKET PASSWORD=$TASK_PASSWORD Email=$EMAIL --capabilities CAPABILITY_IAM


    

     
