name: 'CI/CD'
on:
  push:
    branches:
    - master
    paths:
    - '_build_flag'
jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: .
      CG_TOKEN: ${{ secrets.CG_TOKEN }}
      AWS_REGION: us-east-1
      S3BUCKET: mikedevopsbucket
    
    steps:
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout Code
      uses: actions/checkout@v1
      
    - name: Prep package.zip 
      run: |
          npm install -D https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
          python3 -m venv package
          source package/bin/activate
          pip install requests
          cd package/lib/python3.8/site-packages
          zip -r9 ${OLDPWD}/package.zip .
          cd $OLDPWD
          zip -g package.zip main.py

    - name: Download Dependencies
      run: |
          npm install -D https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
          pip install awscli 
          
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${AWS_REGION}  
    
    - name: Download Dependencies
      run: |
          npm install -D https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
          pip install awscli   
          
    - name: Run Cloudguard Proact
      run: |
          cloudguard proact -C template.cft -t ${CG_TOKEN}
    
    - name: Upload yml output
      uses: actions/upload-artifact@v2
      with:
       name: cloudguard_output.yml
       path: ./cloudguard_output/CloudGuardScanResults.yaml
   
    - name: Upload html output
      uses: actions/upload-artifact@v2
      with:
       name: cloudguard_output.html
       path: ./cloudguard_output/CloudGuardScanReport.html
  
    - name: Run Cloudguard FSP
      run: |
          cloudguard fsp add -C template.cft --region ${AWS_REGION}
          ls
    
     
     
